name: Test misty-cli from AUR

on:
  push:

jobs:
  test:
    runs-on: archlinux-latest
    steps:
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm git sudo base-devel fakeroot

      - name: Setup non root user
        run: |
          usermod -m -s /bin/bash builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

      - name: Install misty-cli
        run: |
          su - builder -c "git clone https://aur.archlinux.org/misty-cli.git"
          su - builder -c "cd misty-cli && makepkg -si --noconfirm"

      - name: Run misty-cli
        run: |
          misty-cli
