name: Test misty-cli

on:
  push:
  pull_request:

jobs:
  test-extras:
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y bash curl grep findutils chafa

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install misty-cli
        run: |
          sudo install -m 755 misty-cli.sh /usr/bin/misty-cli

      - name: Setup python3
        uses: actions/setup-python@v6

      - name: Test extra misty-loop.py
        run: |
          python3 extras/misty-loop.py --istesting True

