name: Test Misty CLI App

on:
  push:
  workflow_dispatch:

jobs:
  testapp:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y curl grep findutils chafa

      - name: Run app
        run: |
          /bin/bash ./misty-cli.sh