name: Test misty-cli

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y bash curl grep findutils chafa

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run misty-cli
        run: |
          chmod +x misty-cli.sh
          bash ./misty-cli.sh --size=40x
